#ifndef CONFIG_H
#define CONFIG_H

/* Constants -- do not modify */

#define I2C_DRIVER_ASYNC (0)
#define I2C_DRIVER_SYNC (1)

#define OLED_DRIVER_SSD1306 (1)
#define OLED_DRIVER_SH1106 (2)

/* End of constants */


#define I2C_DRIVER (I2C_DRIVER_SYNC)
#define I2C_CLOCK (400000L)

#define OLED_DRIVER (OLED_DRIVER_SH1106)
#define OLED_DRAW_BUFFER_SIZE (8)

#define DISPLAY_A_ADDRESS (0x7A)
#define DISPLAY_B_ADDRESS (0x78)


#define CALIBRATION_ZERO_PORT (PORTB)
#define CALIBRATION_ZERO_PIN (PINB)
#define CALIBRATION_ZERO_P (PB4)

#define CALIBRATION_REF_PORT (PORTB)
#define CALIBRATION_REF_PIN (PINB)
#define CALIBRATION_REF_P (PB3)

#define INCLUDE_CALIBRATION (1)


#define ADC_CHANNEL_L_NEEDLE (0)
#define ADC_CHANNEL_L_PEAK (2)
#define ADC_CHANNEL_R_NEEDLE (1)
#define ADC_CHANNEL_R_PEAK (3)


#define NEEDLE_RESOLUTION (128)
#define ZERO_VU_ANGLE (181)

#define PEAK_LEVEL (6.31)


#define ENABLE_SPLASH_SCREEN (0)
#define SPLASH_SCREEN_TIME_MS (3000)

#define DISPLAY_LEFT_FLIPPED (0)
#define DISPLAY_RIGHT_FLIPPED (0)


#endif /* CONFIG_H */
